### ISSUE TITLE
Suitable for use in 32 bit MCUs like the ARM Cortex M4 ?

### ISSUE THREAD

**Issue by zinahe** [hadipourh/KeeLoq#1]
Hi,

Thank you for sharing the code on GitHub and also making it available as open-source. I haven't had a chance to study the code in detail, but do you think your implementation can be used in 32 bit MCUs ?

Thanks,

**Comment by hadipourh** [comment]
Hello,

You're welcome! 
Frankly, KeeLoq has been originally designed for optimum performance on 8-bit MCUs. In addition, I wrote these codes, in order to analyse KeeLoq, from the security point of view, and the performance has not been considered as the main goal. 
If you want to use ARM Cortex-M3, and you don't have to use KeeLoq as the encryption algorithm, it might be better to use another cipher which has been designed with efficient implementation on 32-bit MCUs in mind, from design phase, such as [Chasekey](https://eprint.iacr.org/2014/386.pdf).
Anyway, if you want to implement KeeLoq on 32-bit ARM MCU, the following links may be more useful than my implementations for you: 
http://www.pittnerovi.com/jiri/hobby/electronics/keeloq/
http://www.pittnerovi.com/jiri/hobby/electronics/rfm22b/index.html

Good luck!

**Comment by zinahe** [comment]
Thank you for the reply and pointers. May main goal is to learn and hopefully start using encryption in my hobby projects. I'll definitely check them out.

Cheers,
